
'../../middlewares/authFacebook'
'../../middlewares/authGoogle'

import {Request,Response,NextFunction,Router} from 'express'
import passport from 'passport';

import { check } from 'express-validator'

import { isLoggedIn } from '../../middlewares/isLogged';
import { validateFields } from '../../middlewares/validateFields';
import { validateJwt } from '../../middlewares/validateJwt';
import { login } from '../../controllers/auth'
import { existEmail } from '../../helpers/existEmailUser';
import { validPass } from '../../helpers/regexPass';
import { userAdmin } from '../../middlewares/validateRoles';
import { storage } from '../../middlewares/multerConfig';
import {
    addUser,
    deleteAllUsers,
    deleteUser,
    getUser,
    getUsers,
    googleSuccess,
    googleFailure,
    facebookSuccess,
    noAuth,
    updateDoc,
    updateUser,
    logoutFacebook,
    logoutGoogle,
} from '../../controllers/userController';
import { changePassword, restorePassword } from '../../helpers/restorePass';

const router: Router = Router();

/** 
 * validateJwt - Verify that a token is included in the request.  
 * validateFields - validates errors generated by express-validator
 */
/** ruta base API
 * http:localhost:3000/v1/
 */

/**
 * @swagger 
 * components:
 *  schemas:
 *    User:
 *      type: object  
 *      properties:
 *        id:
 *          type: string
 *          description: autogenerado id del usuario
 *        name:
 *          type: string
 *          description: name of user
 *        email:
 *          type: string
 *          description: email of user
 *        password: 
 *          type: string
 *          description: password user encripted
 *        img:
 *          type: string
 *          description: img or avatar of user
 *        facebook:
 *          type: boolean
 *          description: the users can authenticate with facebook
 *        google:
 *          type: boolean
 *          description: the users can authenticate with google
 *        createAt:
 *          type: string
 *          description: Date of user was create
 *        state:
 *          type: boolean
 *          description: When an user is created its state is true
 *      required: 
 *        - name
 *        - email
 *        - password
 *      example:
 *        id: 5d5015069d894b19b91c71f1
 *        name: SOFIA 
 *        description: i have to do something 
 *    UserNotFound:
 *      type: object
 *      properties:
 *        msg:
 *          type: string
 *          description: a message for the not found user 
 *  parameters: 
 *    userId:
 *      in: path
 *      name: id
 *      required: true
 *      schema:
 *        type: string
 *      description: the user id
 */

/**
 * @swagger
 * tags:
 *  name: Users
 *  description: Users endpoints 
 */

/**
 * @swagger 
 *  /users:
 *  get: 
 *    summary: Muestra todos los usuarios que existen en la API
 *    tags: [Users]
 *    responses:
 *      200:
 *        description: Listado de usuarios
 *        content:
 *          application/json:
 *            schema:
 *              type: array
 *              items:
 *                $ref: '#/components/schemas/User'
 */

router.get('/users',validateJwt,userAdmin,getUsers)
router.get('/user/:id',/* validateJwt ,userAdmin,*/getUser)

/**
 * @swagger
 * /user:
 *  post:
 *    summary: create a new user
 *    tags: [Users]
 *    requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: '#/components/schemas/User'
 *    responses:
 *      200:
 *        description: User successfully created
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/User'
 *      500:
 *        description: Some server error
 *        
 */

router.post('/user',storage.single('img'),[
  check('email')
    .custom(existEmail),
  check('email','Email is not valid')
    .isEmail(),
  check('password')
    .custom(validPass)
    .isLength({ min: 5 })
    .withMessage('must be at least 5 chars long'),
  validateFields
],addUser)

/** ruta login */
router.post('/user/login',login)

/**
 * @swagger
 * /user/{id}: 
 *  get:
 *    summary: Get a user by id
 *    tags: [Users]
 *    parameters:
 *      - $ref: '#components/parameters/userId'
 *    responses:
 *      200: 
 *        description: user was found  
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schema/user'    
 *      404:  
 *        description: user was not found
 *        content: 
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/UserNotFound'
 *                 
 */
router.put('/user/:id', storage.single('img'),updateUser)

/** This route is use to send one link to email user to restore password */
router.post('/restore-password',restorePassword) 
/** This route is use to add new password */
router.post('/password-reset/:idUser',changePassword)

router.delete('/user/:id',
  validateJwt,
  /* userAdmin, */
  validateFields,
  deleteUser)
router.delete('/all-users',/* validateJwt, validateFields, */deleteAllUsers)

/* Test queries findOne */
// router.get('/only-doc',validPass)
router.put('/update-doc',updateDoc)


/** Facebook */
router.get('/auth/facebook',passport.authenticate('sign-up-facebook',{scope:['email']}));
router.get('/auth/facebook/login',
  passport.authenticate('sign-up-facebook', {failureRedirect: '/v1/login' }),
  (req:Request, res:Response)=>{
    res.redirect('/v1/facebook-ok')
  });

router.get('/login',noAuth)
router.get('/facebook-ok',isLoggedIn,facebookSuccess) 

/** google  */
router.get('/auth/google',passport.authenticate('sign-up-google',{scope:['email','profile']}));
router.get('/auth/google/login',passport.authenticate('sign-up-google',{failureRedirect:'/v1/auth/google/failure'}),
(req:Request,res:Response)=>{
  res.redirect('/v1/google-ok')
})

router.get('/google-ok',isLoggedIn,googleSuccess)
router.get('/auth/google/failure',googleFailure);

/** logout google */
router.get('/logout/google',logoutGoogle)
/** logout facebook */
router.get('/logout/facebook',logoutFacebook);

/** No loggedIn google & facebook*/
router.get('/home',(req:Request,res:Response)=>{
  res.send('You are not logged in');
})


export default router;

